### ISSUE TITLE
Automagically detect SQL cluster names

### ISSUE THREAD

**Issue by Teutenberg** [Teutenberg/DBAid#1]
checkmk and configg should detect SQL cluster names to connect to. Right now, these projects won't connect to clusters.

**Comment by thecosmictrickster** [comment]
1. Query HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL
   Each entry is an installed instance. Get value from <Data>

2. Query HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\<Data>\Cluster
   <Data> from ClusterName key has VNN.
   If HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\<Data>\Cluster does not exist, not a clustered instance.

**Comment by thecosmictrickster** [comment]
Works for Windows 2008 R2+
Import-Module FailoverClusters
$sqlcluster = "WindowsClusterNameGoesHere"
$sqlinstances = Get-ClusterResource -cluster $sqlcluster | ? { $_.ResourceType -like "SQL Server"} | Get-ClusterParameter -cluster $sqlcluster VirtualServerName,InstanceName | Group-Object ClusterObject | Select @{ Name = "SQLInstance";Expression = { [string]::join("\",($_.Group | Select -expandproperty Value)) } }
$sqlinstances.sqlinstance

**Comment by thecosmictrickster** [comment]
This command will return an object of type System.Array with a list of cluster nodes:
```
Import-Module FailoverClusters
$sqlcluster = "WindowsClusterNameGoesHere"
$clusternodes = Get-ClusterNode -cluster $sqlcluster
$clusternodes | % { $_.Name }
```

**Comment by thecosmictrickster** [comment]
Need to put logic in to detect if being run on a cluster - if not, exit gracefully.
Need to have logic to detect if on a cluster node (without knowing cluster VNNs) and retrieve VNNs.

**Comment by thecosmictrickster** [comment]
Functions at https://github.com/thecosmictrickster/DBAid_Deployment

**Comment by Teutenberg** [comment]
Added the code here: https://github.com/Teutenberg/DBAid/blob/master/checkmk/set-app-config-defaults.ps1
Right now it only lists the local instances, but the idea is it will setup the app.config file with default settings.
