### ISSUE TITLE
Change console app to .net Core

### ISSUE THREAD

**Issue by Teutenberg** [Teutenberg/DBAid#12]
Use .Net core for compatibility between Windows and Linux.

**Comment by thecosmictrickster** [comment]
Removed low priority tag. This is more important as we are starting to get questions about monitoring SQL instances on Linux. We need to decide whether to go down the .NET Core route for executables or start managing these functions with PowerShell and/or shell scripts.

**Comment by Teutenberg** [comment]
We should move to signed PowerShell scripts. I have moved collector and cofigg to PS scripts. There is a draft CheckMk PS script, it just needs to output in the format CheckMk agent expects.

**Comment by Teutenberg** [comment]
We will need to make sure our PS scripts are compatible with PowerShell Core, https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6

**Comment by Teutenberg** [comment]
duplicate issue to getting DBAid to work with Linux. https://github.com/Teutenberg/DBAid2/issues/4
