### ISSUE TITLE
check_alwayson procedure won't work

### ISSUE THREAD

**Issue by Teutenberg** [Teutenberg/DBAid#2]
check_alwayson procedure needs to be updated. Currently it will not work.

**Comment by thecosmictrickster** [comment]
Won't work in what way exactly?

**Comment by Teutenberg** [comment]
It has not been updated to work with the new database. Code points to missing objects. New table checkmk.config_availability_group needs to be created and proc updated.

**Comment by thecosmictrickster** [comment]
Code updated, pull request created.
