### ISSUE TITLE
Config Genie SQL Agent job sometimes fails

### ISSUE THREAD

**Issue by thecosmictrickster** [Teutenberg/DBAid#25]
ERROR	DBaidAsBuilt	Invalid object name 'master.sys.sysclsobjs'.  Could not use view or function 'sys.audits$' because of binding errors. Unhandled Exception: System.Data.SqlClient.SqlException: Invalid object name 'master.sys.sysclsobjs'.  Could not use view or function 'sys.audits$' because of binding errors.     at local.dbaid.asbuilt.Program.Main(String[] args).  Process Exit Code -532459699.

Next run completes successfully. At very least, add retries to job step. Seen to affect SQL 2008 & SQL 2008 R2.

**Comment by thecosmictrickster** [comment]
If we're only supporting what Microsoft supports, this may become moot after July 2019 (unless it occurs on something newer than SQL 2008).

**Comment by Teutenberg** [comment]
Agree, if not happening on other versions of SQL Server, no point fixing. Use manual workaround mentioned on affect hosts, "add retries to job step".
