### ISSUE TITLE
TempDB has standard defaults applied in [checkmk].[config_database]

### ISSUE THREAD

**Issue by thecosmictrickster** [Teutenberg/DBAid#34]
We can't be having this - we'll be getting alerts for tempdb not getting backed up or having integrity checks done (among other things). 
Either defaults need changing for tempdb, tempdb gets excluded from table, or relevant check scripts have "database_name <> N'tempdb'". Or a combination of first & third options.

**Comment by thecosmictrickster** [comment]
Code updated, pull request logged.

**Comment by Teutenberg** [comment]
Fix merged into master
